name: GitHub Actions Demo
run-name: Deloying Enviro-Watch!
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Updating system...
        run: sudo apt update && sudo apt upgrade
      - name: "Cloning Repository..."
        uses: actions/checkout@v4.2.2
      - name: Installing dependencies...
        run:  |
          chmod +x install.sh
          sudo apt-get install python3 -y
          sudo apt-get install python3-pip --yes
          ls -l

        
